server:
  port: 8084
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Welcome123$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
jwt:
  secret: secretKey
  token-url: 
    validate: http://customer-service/validate/
    
restaurant:
  service:v
    search-url:
      restaurant: http://restaurant-service/restaurant/{restaurantId}
    review-url: 
      restaurant: http://restaurant-service/restaurant/{restaurantId}/review
      
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.springframework: ERROE
    com.eatza: DEBUG
      